### ISSUE TITLE
Missing files - cannot compile kernel

### ISSUE THREAD

**Issue by carter-yagemann** [TJAndHisStudents/Griffin-Trace#1]
Several kernel files are missing from this repo:

        include/uapi/linux/netfilter/xt_CONNMARK.h
        include/uapi/linux/netfilter/xt_DSCP.h
        include/uapi/linux/netfilter/xt_MARK.h
        include/uapi/linux/netfilter/xt_RATEEST.h
        include/uapi/linux/netfilter/xt_TCPMSS.h
        include/uapi/linux/netfilter_ipv4/ipt_ECN.h
        include/uapi/linux/netfilter_ipv4/ipt_TTL.h
        include/uapi/linux/netfilter_ipv6/ip6t_HL.h
        net/netfilter/xt_DSCP.c
        net/netfilter/xt_HL.c
        net/netfilter/xt_RATEEST.c
        net/netfilter/xt_TCPMSS.c

This is probably related to: https://raspberrypi.stackexchange.com/a/13739

I'll open a pull request to fix this.

**Comment by trentjaeger** [comment]
Thanks, Carter.

We’ll look into this.

Regards,
Trent.
----------------------------------------------
Trent Jaeger
Professor, CSE Department
Pennsylvania State University
W359 Westgate Bldg, University Park, PA 16802
Email: tjaeger@cse.psu.edu<mailto:tjaeger@cse.psu.edu>
Ph: (814) 865-1042, Fax: (814) 865-3176
URL: http://www.trentjaeger.com

On Jan 17, 2019, at 4:04 PM, Carter Yagemann <notifications@github.com<mailto:notifications@github.com>> wrote:


Several kernel files are missing from this repo. To list a few:

    include/uapi/linux/netfilter/xt_CONNMARK.h
    include/uapi/linux/netfilter/xt_DSCP.h
    include/uapi/linux/netfilter/xt_MARK.h
    include/uapi/linux/netfilter/xt_RATEEST.h
    include/uapi/linux/netfilter/xt_TCPMSS.h
    include/uapi/linux/netfilter_ipv4/ipt_ECN.h
    include/uapi/linux/netfilter_ipv4/ipt_TTL.h
    include/uapi/linux/netfilter_ipv6/ip6t_HL.h
    net/netfilter/xt_DSCP.c
    net/netfilter/xt_HL.c
    net/netfilter/xt_RATEEST.c
    net/netfilter/xt_TCPMSS.c


This is probably related to: https://raspberrypi.stackexchange.com/a/13739<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fraspberrypi.stackexchange.com%2Fa%2F13739&data=02%7C01%7Ctrj1%40psu.edu%7C0ae86edbbc104488183b08d67cc13382%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636833566572410013&sdata=sMY4n3woeSpOJKhFS6yHj%2BX7vmiv8z79gI3ibpXZTaA%3D&reserved=0>

I'll open a pull request to fix this.

**Comment by mitthu** [comment]
I have added the missing files. Let me know if it still fails to compile.

**Files added**
```bash
git add .gitignore \
	include/uapi/linux/netfilter/xt_CONNMARK.h \
	include/uapi/linux/netfilter/xt_DSCP.h \
	include/uapi/linux/netfilter/xt_MARK.h \
	include/uapi/linux/netfilter/xt_RATEEST.h \
	include/uapi/linux/netfilter/xt_TCPMSS.h \
	include/uapi/linux/netfilter_ipv4/ipt_ECN.h \
	include/uapi/linux/netfilter_ipv4/ipt_TTL.h \
	include/uapi/linux/netfilter_ipv6/ip6t_HL.h \
	net/netfilter/xt_DSCP.c \
	net/netfilter/xt_HL.c \
	net/netfilter/xt_RATEEST.c \
	net/netfilter/xt_TCPMSS.c \
	tools/perf/scripts/perl/Perf-Trace-Util/lib/ \
	tools/perf/scripts/python/Perf-Trace-Util/lib/
```

**Comment by carter-yagemann** [comment]
This works on my end, thanks. Closing issue.
